### PR TITLE
Elasticsearch5

### PR DESCRIPTION
**Pull request by fgrosse**
Update the plugin to work on [5.0.0-alpha3](https://www.elastic.co/blog/elasticsearch-5-0-0-alpha3-released) for early adopters and testing.
I based the plugin upgrade on the official [analysis-icu plugin](https://github.com/elastic/elasticsearch/tree/v5.0.0-alpha3/plugins/analysis-icu)

Notable changes:
- `org.xbib.elasticsearch.MapperTestUtils` is not necessary anymore due to `org.elasticsearch.test.ESTestCase`

### CODE REVIEW

**Comment by jprante** [comment]
Thanks for the pull request. 

Currently, ES 5 is alpha. I don't feel it makes sense to publish a series of alpha builds right now. I hope beta phase begins soon with stabilized APIs.

Beside that, I want to keep log4j2 and the mapper test utils for the sake of my own projects. The gradle machinery around ESTestCase feels too heavyweight regarding dependencies, so I decided to run my own gradle integration tests for plugins without any dependencies.

**Comment by fgrosse** [comment]
I am looking forward to the beta as well. Just wanted to share what I have so far in case somebody also wants to try this out really early.

About log4j2 and the tests: I was just copying what I saw in the official repo. I didnt actually intend to change any dependencies more than I need to make it work.

Lets revisit this pull request on beta or the major release then :)

**Comment by fgrosse** [comment]
Elasticseach 5.0.0 was released yesterday so now this PR can move forward. I merged the current master into this branch to resolve the merge conflicts.

Before doing that in 3868467a1f5814daddebfb994efb2f8850f557a0 all tests were green for me locally. Now I get a jar hell and `java.lang.IllegalStateException: path.home is not configured`. Unfortunately my java got a bit rusty and I don't quite know at this point how to fix this easily so some advice would be very welcome.

**Comment by jprante** [comment]
Version 5.1.1.0 has been released. Thanks for the work on ES 5 alpha.

**Pull request closed without merging**
