### PR TITLE
version for elasticsearch 2.3.1

### PR DESCRIPTION
**Pull request by awislowski**
Version for elasticsearch 2.3.1

### CODE REVIEW

**Comment by mablae** [comment]
I am just curious what's behind this versioning scheme? 

Why a release for every ES version? Just to keep version numbers in sync? 
Other ES plugins only maintain a 1.x and a 2.x branch like the popular kopf plugin.

I find the versioning table kinda confusing.

**Comment by awislowski** [comment]
Elasticsearch plugins for versions 2.x need to be released for every elasticsearch version.

**Comment by marek-obuchowicz** [comment]
Bump... 2.3.2 is released, lack of plugin is preventing us from upgrade several other components, incl. marvel...

**Comment by jprante** [comment]
Done with release of 2.3.2.0

**Pull request closed without merging**
