### PR TITLE
Update for ES 2.2.0

### PR DESCRIPTION
**Pull request by apanimesh061**
Kindly see if the changes made are alright.

### CODE REVIEW

**Comment by jprante** [comment]
The pull request is not ok because

- it changes Travis to your repo
- it uses JDK 8 but ES 2.2.0 requires still JDK7

I will update to ES 2.2.0 asap

**Comment by apanimesh061** [comment]
Oh ok.

Thanks for that.

**Comment by jprante** [comment]
Merged with 6a92cda32c7e2a80ccbf6b6500059b0e76745353, released plugin verion 2.2.0.0

**Comment by mablae** [comment]
@jprante Awesome. Thanks. Nothing blocks me from Upgrading our 1.7 ES Cluster now :)

**Pull request closed without merging**
